version: '3'

services:
  web:
    container_name: web
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/app
    command: python manage.py runserver 0.0.0.0:8000
    networks:
      - app

  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - app

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    networks:
      - app

volumes:
  prometheus-data:
  grafana-data:

networks:
  app:
